apiVersion: enmasse.io/v1beta1
kind: AddressSpace
metadata:
  labels:
    addressSpaceType: standard
    type: address-space
  name: standard-products-catalog
spec:
  type: standard
  #plan: standard-small
  plan: standard-default-paging
  authenticationService:
    name: db-authservice
  endpoints:
  - name: messaging
    service: messaging
    expose:
      type: route
      routeServicePort: amqps
      routeTlsTermination: passthrough
      routeHost: products-catalog-messaging.belux-5c19b80d0b42bf06f50309d5c8a080e8-0000.eu-de.containers.appdomain.cloud
    cert:
      provider: openshift
    exports:
    - kind: ConfigMap
      name: standard-products-catalog-cm
