apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbac-amq-online-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rbac-amq-online
subjects:
- kind: ServiceAccount
  name: address-space-controller
  namespace: amq-online-infra