apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


generatorOptions:
 disableNameSuffixHash: true

commonLabels:
  environment: development

namespace: products-catalog

bases:
- ../../../base/products-catalog/

secretGenerator:
- name: server-secret
  files:
    - crt/tls.crt
    - crt/tls.key
  type: "kubernetes.io/tls"
- name: remote-secret
  files:
  - cert=crt/messaging-endpoint_cluster-1d9e_cert.crt
  - key=crt/messaging-endpoint_cluster-1d9e.key

patchesStrategicMerge:
- amq-online/patch-address-space-standard-products-catalog.yaml
- amq-online/patch-address-myqueue.yaml
