apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: products-catalog-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: products-catalog
  source:
    repoURL: https://github.com/rahmed-rh/products-microservice.git
    targetRevision: HEAD
    path: overlays/products-catalog/development
  syncPolicy:
    automated:
      prune: true
# changes that are made to the live cluster will trigger automated sync
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: products-catalog
