apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
 disableNameSuffixHash: true

namespace: products-catalog


resources:
  - namespace.yaml
  - amq-online/role.yaml
  - amq-online/role-binding.yaml
  - amq-online/messaging-users.yaml
  - amq-online/address-space-standard-products-catalog.yaml
  - amq-online/address-myqueue.yaml
