apiVersion: enmasse.io/v1beta1
kind: AddressSpace
metadata:
  name: standard-products-catalog
spec:
  authenticationService:
    name: standard-authservice
  connectors:
  - name: remote
    endpointHosts:
    - host: messaging-2.apps.cluster-107d.gcp.testdrive.openshift.com
      port: 443
    tls:
      caCert:
        valueFromSecret:
          name: remote-secret
          key: tls.crt
      clientCert:
        valueFromSecret:
          name: server-secret
          key: tls.crt
      clientKey:
        valueFromSecret:
          name: server-secret
          key: tls.key
    credentials:
      username:
        value: demo-user
      password:
        value: password
    addresses:
    - name: remoteQueue
      pattern: "*"
  endpoints:
  - name: messaging
    service: messaging
    expose:
      type: route
      routeServicePort: amqps
      routeTlsTermination: passthrough
      routeHost: messaging-1.apps.cluster-107d.gcp.testdrive.openshift.com
    exports:
    - kind: ConfigMap
      name: standard-products-catalog-cm
