apiVersion: enmasse.io/v1beta1
kind: AddressSpace
metadata:
  name: standard-products-catalog
spec:
  authenticationService:
    name: standard-authservice
  # connectors:
  # - name: remote
  #   endpointHosts:
  #   - host: messaging-1.apps.cluster-8656.8656.sandbox114.opentlc.com
  #     port: 443
  #   tls:
  #     caCert:
  #       valueFromSecret:
  #         name: remote-secret
  #         key: tls.crt
  #     clientCert:
  #       valueFromSecret:
  #         name: server-secret
  #         key: tls.crt
  #     clientKey:
  #       valueFromSecret:
  #         name: server-secret
  #         key: tls.key
  #   credentials:
  #     username:
  #       value: demo-user
  #     password:
  #       value: password
  #   addresses:
  #   - name: remoteQueue
  #     pattern: "*"
  endpoints:
  - name: messaging
    service: messaging
    expose:
      type: route
      routeServicePort: amqps
      routeTlsTermination: passthrough
      routeHost: products-catalog-messaging.belux-5c19b80d0b42bf06f50309d5c8a080e8-0000.eu-de.containers.appdomain.cloud
    exports:
    - kind: ConfigMap
      name: standard-products-catalog-cm
