apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rbac-amq-online
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps","secrets" ]
    verbs: [ "create","get", "update", "patch" ]